apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequirednamespace
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredNamespace
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequirenamespace
        violation[{ "msg" : msg }] {
          input.review.object.metadata.name == "dummy"
          input.review.operation == "DELETE"
          msg := sprintf("Deletion of the namespace %v is not allowed.", [input.review.object.metadata.name])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredNamespace
metadata:
  name: deny-namespace-deletion
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    rules:
    - operations: ["DELETE"]
